# Generated by Django 3.1.7 on 2021-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0002_auto_20210415_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='xray',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
