# Generated by Django 3.1.7 on 2021-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0005_auto_20210418_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='xray',
            field=models.ImageField(null=True, upload_to='xray/'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='xray_predicted',
            field=models.ImageField(null=True, upload_to='xray_predicted/'),
        ),
    ]
