# Generated by Django 3.1.7 on 2021-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0006_auto_20210418_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='xray_predicted',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='predict',
            name='xray_truth',
            field=models.ImageField(blank=True, null=True, upload_to='truth_xray/'),
        ),
    ]
