# Generated by Django 3.1.7 on 2021-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicts', '0007_auto_20210418_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='xray_predicted',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
