# Generated by Django 3.1.7 on 2021-07-26 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ages', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('smoke', models.CharField(blank=True, max_length=200, null=True)),
                ('relative_a', models.FloatField(blank=True, default='0.5', max_length=6)),
                ('relative_b', models.FloatField(default=0, max_length=6)),
                ('FVC_base', models.FloatField(default=3000.0, max_length=4)),
                ('week_base', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=100, max_length=4)),
                ('week_start', models.IntegerField(default=0)),
                ('week_end', models.IntegerField(default=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPatientImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=255, upload_to='pf/')),
                ('ppatient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfds.ppatient')),
            ],
        ),
        migrations.CreateModel(
            name='FVC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(max_length=200)),
                ('fvc_value_final', models.CharField(max_length=200)),
                ('confidence', models.CharField(max_length=200)),
                ('ppatient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfds.ppatient')),
            ],
        ),
    ]
